## -*- coding: utf-8 -*-

"""
/***************************************************************************
 AgriculturePrecision
                                 A QGIS plugin
 Chaines de traitement
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-21
        copyright            : (C) 2020 by ASPEXIT
        email                : cleroux@aspexit.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'ASPEXIT'
__date__ = '2020-07-21'
__copyright__ = '(C) 2020 by ASPEXIT'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'


from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsApplication,
                       QgsVectorLayer,
                       QgsRasterLayer,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterVectorDestination)



from qgis import processing 
from math import sqrt
import os

class ZonageClassification(QgsProcessingAlgorithm):
    """
    
    """ 

    OUTPUT= 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_CONTOUR = 'INPUT_CONTOUR'
    INPUT_METHOD = 'INPUT_METHOD'
    INPUT_N_CLASS = 'INPUT_N_CLASS'
    TEMP_PATH = 'TEMP_PATH'


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_CONTOUR,
                self.tr('Contour de la parcelle')
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Raster à zoner')
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.TEMP_PATH,
                self.tr('Dossier du projet'),
            )
        )
        
        self.addParameter(
            QgsProcessingParameterEnum(
                self.INPUT_METHOD,
                self.tr('Choix de la méthode de classification'),
                ['Quantiles', 'Intervalles Egaux', '(Jenks)', '(K-means (Iterative Minimum Distance))']                
            )
        )
       
        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_N_CLASS, 
                self.tr('Nombre de classes'),
                QgsProcessingParameterNumber.Integer,
                4,
                False,
                2,
                10
            )
        )
        
        self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT,
                self.tr('Parcelle zonee')
            )
        )
        
        

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        
        contour = self.parameterAsVectorLayer(parameters,self.INPUT_CONTOUR,context)
        layer = self.parameterAsRasterLayer(parameters,self.INPUT,context)
        output_path = self.parameterAsOutputLayer(parameters,self.OUTPUT,context)
        temp_path = self.parameterAsString(parameters,self.TEMP_PATH,context)+'\\temporary'
        
        nombre_classes = self.parameterAsInt(parameters,self.INPUT_N_CLASS,context)
        method = self.parameterAsEnum(parameters,self.INPUT_METHOD,context)
        
        # Tampon
        alg_params = {
            'DISSOLVE': False,
            'DISTANCE': 10,
            'END_CAP_STYLE': 0,
            'INPUT': parameters['INPUT_CONTOUR'],
            'JOIN_STYLE': 0,
            'MITER_LIMIT': 2,
            'SEGMENTS': 5,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        tampon = processing.run('native:buffer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)


        # Découper un raster selon une couche de masque
        alg_params = {
            'ALPHA_BAND': False,
            'CROP_TO_CUTLINE': True,
            'DATA_TYPE': 0,
            'EXTRA': '',
            'INPUT': parameters['INPUT'],
            'KEEP_RESOLUTION': False,
            'MASK': tampon['OUTPUT'],
            'MULTITHREADING': False,
            'NODATA': None,
            'OPTIONS': '',
            'SET_RESOLUTION': False,
            'SOURCE_CRS': 'ProjectCrs',
            'TARGET_CRS': 'ProjectCrs',
            'X_RESOLUTION': None,
            'Y_RESOLUTION': None,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        coupe = processing.run('gdal:cliprasterbymasklayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)


        # Classification raster
        alg_params = {
            'INPUT': coupe['OUTPUT'],
            'INPUT_METHOD': method,
            'INPUT_N_CLASS': nombre_classes,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        classe = processing.run('Agriculture de précision:Classification raster', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # r.neighbors
        alg_params = {
            '-a': False,
            '-c': False,
            'GRASS_RASTER_FORMAT_META': '',
            'GRASS_RASTER_FORMAT_OPT': '',
            'GRASS_REGION_CELLSIZE_PARAMETER': 0,
            'GRASS_REGION_PARAMETER': None,
            'gauss': None,
            'input': classe['OUTPUT'],
            'method': 2,
            'quantile': '',
            'selection': classe['OUTPUT'],
            'size': 3,
            'weight': '',
            'output': temp_path+'.tif'
        }
        voisins = processing.run('grass7:r.neighbors', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
 
        # Polygoniser (raster vers vecteur)
        alg_params = {
            'BAND': 1,
            'EIGHT_CONNECTEDNESS': False,
            'EXTRA': '',
            'FIELD': 'DN',
            'INPUT': temp_path+'.tif', #voisins['output'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        polygones = processing.run('gdal:polygonize', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Réparer les géométries
        alg_params = {
            'INPUT': polygones['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        repare = processing.run('native:fixgeometries', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Intersection
        alg_params = {
            'INPUT': parameters['INPUT_CONTOUR'],
            'INPUT_FIELDS': None,
            'OVERLAY': repare['OUTPUT'],
            'OVERLAY_FIELDS': None,
            'OVERLAY_FIELDS_PREFIX': '',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        intersection = processing.run('native:intersection', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Supprimer champ(s)
        alg_params = {
            'COLUMN': 'fid',
            'INPUT': intersection['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        champ_suppr = processing.run('qgis:deletecolumn', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # v.clean
        alg_params = {
            '-b': False,
            '-c': False,
            'GRASS_MIN_AREA_PARAMETER': 0.0001,
            'GRASS_OUTPUT_TYPE_PARAMETER': 0,
            'GRASS_REGION_PARAMETER': None,
            'GRASS_SNAP_TOLERANCE_PARAMETER': -1,
            'GRASS_VECTOR_DSCO': '',
            'GRASS_VECTOR_EXPORT_NOCAT': False,
            'GRASS_VECTOR_LCO': '',
            'input': champ_suppr['OUTPUT'],
            'threshold': '250',
            'tool': [10],
            'type': [0,1,2,3,4,5,6],
            'error': QgsProcessing.TEMPORARY_OUTPUT,
            'output': temp_path+'.shp'
        }
        clean = processing.run('grass7:v.clean', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Supprimer champ(s)
        alg_params = {
            'COLUMN': 'fid',
            'INPUT': temp_path+'.shp',#clean['output'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        champ_suppr = processing.run('qgis:deletecolumn', alg_params, context=context, feedback=feedback, is_child_algorithm=True)


        # Statistiques de zone
        alg_params = {
            'COLUMN_PREFIX': '_',
            'INPUT_RASTER': parameters['INPUT'],
            'INPUT_VECTOR': champ_suppr['OUTPUT'],
            'RASTER_BAND': 1,
            'STATS': [2,4]
        }
        stat = processing.run('qgis:zonalstatistics', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # v.generalize
        alg_params = {
            '-l': True,
            '-t': False,
            'GRASS_MIN_AREA_PARAMETER': 0.0001,
            'GRASS_OUTPUT_TYPE_PARAMETER': 0,
            'GRASS_REGION_PARAMETER': None,
            'GRASS_SNAP_TOLERANCE_PARAMETER': -1,
            'GRASS_VECTOR_DSCO': '',
            'GRASS_VECTOR_EXPORT_NOCAT': False,
            'GRASS_VECTOR_LCO': '',
            'alpha': 1,
            'angle_thresh': 3,
            'beta': 1,
            'betweeness_thresh': 0,
            'cats': '',
            'closeness_thresh': 0,
            'degree_thresh': 0,
            'input': stat['INPUT_VECTOR'],
            'iterations': 1,
            'look_ahead': 7,
            'method': 0,
            'reduction': 50,
            'slide': 0.5,
            'threshold': 1,
            'type': [0,1,2],
            'where': '',
            'error': QgsProcessing.TEMPORARY_OUTPUT,
            'output': parameters['OUTPUT']
        }
        generalise = processing.run('grass7:v.generalize', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        '''del voisins
        del clean
        
        if os.path.isfile(temp_path+'.tif'):
            os.remove(temp_path+'.tif')
        if os.path.isfile(temp_path+'.shp'):
            os.remove(temp_path+'.shp')'''
        
        
        return{self.OUTPUT : output_path} 
   
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Zonage par classification"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr('Action sur Raster')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'action_sur_raster'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ZonageClassification()
