## -*- coding: utf-8 -*-

"""
/***************************************************************************
 AgriculturePrecision
                                 A QGIS plugin
 Chaines de traitement
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-21
        copyright            : (C) 2020 by ASPEXIT
        email                : cleroux@aspexit.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'ASPEXIT'
__date__ = '2020-07-21'
__copyright__ = '(C) 2020 by ASPEXIT'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'


from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsApplication,
                       QgsVectorLayer,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterField,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterRasterDestination)



from qgis import processing 
from .functions.general import *

class InterpolationPoints(QgsProcessingAlgorithm):
    """
    
    """ 

    OUTPUT= 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_METHOD = 'INPUT_METHOD'
    INPUT_PIXEL = 'INPUT_PIXEL'
    INPUT_POWER = 'INPUT_POWER'
    FIELD = 'FIELD'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Couche vecteur à traiter'),
                [QgsProcessing.TypeVectorPoint]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterEnum(
                self.INPUT_METHOD,
                self.tr('Methode'),
                ['Thiessen','Voronoi','Delaunay','Pondération inverse à la distance']
            )
        )
        
        self.addParameter( 
            QgsProcessingParameterField( 
                self.FIELD, 
                self.tr( "Champ à rasteriser" ), 
                QVariant(),
                self.INPUT,
                type=QgsProcessingParameterField.Numeric
            ) 
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_PIXEL,
                self.tr('Taille du pixel'),
                QgsProcessingParameterNumber.Double,
                0.5
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_POWER,
                self.tr('Puissance (Pondération inverse à la distance)'),
                QgsProcessingParameterNumber.Integer,
                2
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Interpolation')
            )
        )
        
        

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        
        layer = self.parameterAsVectorLayer(parameters,self.INPUT,context)
        output_path = self.parameterAsOutputLayer(parameters,self.OUTPUT,context)
        method = self.parameterAsEnum(parameters,self.INPUT_METHOD,context)
        pixel_size = self.parameterAsDouble(parameters,self.INPUT_PIXEL,context)
        
        if method == 3 :
          # interpolation pondérée inversement à la distance (GRASS)
            alg_params = {
                '-n': False,
                'GRASS_MIN_AREA_PARAMETER': 0.0001,
                'GRASS_RASTER_FORMAT_META': '',
                'GRASS_RASTER_FORMAT_OPT': '',
                'GRASS_REGION_CELLSIZE_PARAMETER': pixel_size, 
                'GRASS_REGION_PARAMETER': parameters[self.INPUT],
                'GRASS_SNAP_TOLERANCE_PARAMETER': -1,
                'column': parameters[self.FIELD],
                'input': parameters[self.INPUT],
                'npoints': None,
                'power': parameters[self.INPUT_POWER],
                'output': parameters[self.OUTPUT]
            }
            raster_layer = processing.run('grass7:v.surf.idw', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            
        else :
            if method in [0,1] :
                if method == 0:
                    # Thiessen polygons
                    alg_params = {
                        'FRAME': 10,
                        'POINTS': parameters[self.INPUT],
                        'POLYGONS': QgsProcessing.TEMPORARY_OUTPUT
                    }
                    polygon_layer = processing.run('saga:thiessenpolygons', alg_params, context=context, feedback=feedback, is_child_algorithm=True)['POLYGONS']
                
                elif method == 1:
                      # Polygones de Voronoï
                    alg_params = {
                        'BUFFER': 0,
                        'INPUT': parameters[self.INPUT],
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }
                    polygon_layer = processing.run('qgis:voronoipolygons', alg_params, context=context, feedback=feedback, is_child_algorithm=True)['OUTPUT']
                  
              
                # Réaliser une enveloppe convexe à partir de points
                alg_params = {
                    'INPUT': parameters[self.INPUT],
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
                enveloppe_convexe = processing.run('Agriculture de précision:Réaliser une enveloppe convexe à partir de points', alg_params, context=context, feedback=feedback, is_child_algorithm=True)


                # Couper
                alg_params = {
                    'INPUT': polygon_layer,
                    'OVERLAY': enveloppe_convexe['OUTPUT'],
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
                layer_to_rasterize = processing.run('native:clip', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            
            if method == 2 :
                
                # Triangulation de Delaunay
                alg_params = {
                    'INPUT': parameters[self.INPUT],
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
                triangulated_layer = processing.run('qgis:delaunaytriangulation', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

                # Joindre les attributs par localisation
                alg_params = {
                    'DISCARD_NONMATCHING': False,
                    'INPUT': triangulated_layer['OUTPUT'],
                    'JOIN': parameters[self.INPUT],
                    'JOIN_FIELDS': None,
                    'METHOD': 1,
                    'PREDICATE': [0],
                    'PREFIX': '',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
                layer_to_rasterize = processing.run('qgis:joinattributesbylocation', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
                
            resolution = pixel_resolution(layer,pixel_size)
            # Rasteriser (vecteur vers raster)
            alg_params = {
                'BURN': None,
                'DATA_TYPE': 5,
                'EXTENT': layer_to_rasterize['OUTPUT'],
                'EXTRA': '',
                'FIELD': parameters[self.FIELD],
                'HEIGHT': resolution[1],
                'INIT': None,
                'INPUT': layer_to_rasterize['OUTPUT'],
                'INVERT': False,
                'NODATA': 0,
                'OPTIONS': '',
                'UNITS': 0,
                'WIDTH': resolution[0],
                'OUTPUT': parameters[self.OUTPUT]
            }
            raster_layer = processing.run('gdal:rasterize', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
                
        return{self.OUTPUT : output_path} 
   
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Interpolation à partir de points"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr('Action sur Vecteurs')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'action_sur_vecteur'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return InterpolationPoints()
